### ISSUE TITLE
Error getting emulator name

### ISSUE THREAD

**Issue by getFran** [AdriaGual/pokemon-pocket-bot#10]
Hi, I can't get the app to work. I keep getting an error indicating that the system cannot find the file specified. I tried debugging a bit and it explodes in get_emulator_name function when trying to set the result variable.

I installed the pokemon dedicated version of LDPlayer on the Desktop and set that folder as the emulator path in the app. I dont know if I am missing something. Thanks.

**Comment by AdriaGual** [comment]
Hmmm can you do an 'adb devices' from any path?

Check also this issue since I feel it can be the same problem.

https://github.com/AdriaGual/pokemon-pocket-bot/issues/1

**Comment by getFran** [comment]
It works like a charm now! I only needed to set the emulator path as environment variable. Thank you very much!
