### ISSUE TITLE
Launch Issue (After recent commits)

### ISSUE THREAD

**Issue by TerpToke** [AdriaGual/pokemon-pocket-bot#14]
Hello again!

Wonderful to see you getting help! <3

Maybe I just don't fully understand merging code as others contribute new commits but as I am attempting to test out the progress being made, the bot no longer populates a UI/doesn't move past the first step. Any help is greatly appreciated. Thank you guys so much for your efforts. I'll thank you a million times over.

I attempted similar ways to run the bot but unfortunately I get this error.

![image_2024-11-09_151321689](https://github.com/user-attachments/assets/bdef582c-e77e-49f9-aa3c-c5099354cf0b)

**Comment by AdriaGual** [comment]
Ohhh it's not your problem, we missed that now we use the module 'requests' to make the API calls.

I updated the requirements.txt, you just need to get the last commit and do another time the `pip install -r requirements.txt`

Hope it helps 🎇

**Comment by TerpToke** [comment]
@AdriaGual Awesome, thank you! That did the trick! I'm going to close the issue but I ran into something that may need to be documented just in case someone else runs into this issue as well (this isn't the first time it's happened so I immediately knew the fix) :

For some reason when numpy v2.1.2 is paired with opencv python v4.9.0.80, a compatibility issue arises for me. The fix is to upgrade opencv python with `pip install opencv_python --upgrade`

Haven't tested the bot yet but after updating the requirements/force upgrading open_cv, the UI generates once again. As always, I appreciate all of your work and support!

![image](https://github.com/user-attachments/assets/a0c74c2c-666e-4366-96b4-9dcc143d42be)
