### ISSUE TITLE
Device not appearing in Device Manager

### ISSUE THREAD

**Issue by henriquepiresmartins** [AdriaGual/pokemon-pocket-bot#29]
I have configured the LDPlayer as requested, and while the device shows up in ADB, it does not appear in Device Manager
![Captura de tela 2024-11-20 093407](https://github.com/user-attachments/assets/1f167bfb-30d3-4be9-8e2c-d2a12e7c8ea9)

**Comment by henriquepiresmartins** [comment]
I managed to solve it: I had to add the LDPlayer path to the environment variables. Please close/delete this issue. Thanks!

**Comment by CyberSardinha** [comment]
I know that this is completed but I'm having the same problem and can't seem to find a way to solve it.

**Comment by henriquepiresmartins** [comment]
> I know that this is completed but I'm having the same problem and can't seem to find a way to solve it.

You need to add adb, or the folder containing adb (for example: the ldplayer folder), to the environment variables.
