### ISSUE TITLE
Can't run py

### ISSUE THREAD

**Issue by superbosz19** [AdriaGual/pokemon-pocket-bot#4]
Can't run py
if not self.image_processor.check_and_click_until_found(self.template_images["VERSUS_SCREEN"], f"{"VERSUS_SCREEN".replace('_', ' ').title()}", running, stop, max_attempts=10): ^ ^^^^^^^^^^^^^
SyntaxError: f-string: expecting '}'

I've tried many methods  T^T
Could you please tell me please

**Comment by AdriaGual** [comment]
Hey @superbosz19! I did a little fix, update the code and try it, after, tell me if it keeps the same error or it changes.

**Comment by superbosz19** [comment]
VERSUS_SCREEN seems to have no problem, but EVENT, MATCH, and SCREEN still have issues.
Perhaps it's RANDOM-MATCH_SCREEN,
BATTLE_BUTTON
I still have the same problem.
The main issue that may arise is the use of overlapping f-strings, which can confuse Python's work.
![Capture](https://github.com/user-attachments/assets/cdfb26fb-0bcd-49fb-b44f-4a934f612c08)

**Comment by superbosz19** [comment]
![image](https://github.com/user-attachments/assets/2ffd8ee7-efe6-4045-b8b0-737c147ea1af)
Awesome, that's cool, I can run python but I can't start the bot or what am I doing wrong?

**Comment by AdriaGual** [comment]
@superbosz19 I see the problem, fixed it!
