### ISSUE TITLE
Loop on game start (look at hand and do not play)

### ISSUE THREAD

**Issue by NomadCHK** [AdriaGual/pokemon-pocket-bot#7]
![image](https://github.com/user-attachments/assets/9ca8c118-12dd-4a46-861a-499b6fcd0740)

it loops looking to the hand and wont play the first pokemon

**Comment by AdriaGual** [comment]
@NomadCHK I checked it, seems like now the card only has the name and the position, but not the info, so it can't play the card
```
  if card.get("info", False) and card["info"]["level"] == 0 and not card["info"]["item_card"]:
      # Log Pokémon being set as active
      self.log_callback(f"🆕 Setting Active Pokémon: **{card['name']}**")
      drag_position((start_x, self.card_y), (self.center_x, self.center_y))
      self.active_pokemon.append(card)
```

![image](https://github.com/user-attachments/assets/4899ac18-3e82-4598-9de7-97020206e666)

**Comment by AdriaGual** [comment]
@NomadCHK Some fixes here and there and it should play the card on the first turn. Can you check it?

**Comment by NomadCHK** [comment]
> @NomadCHK Some fixes here and there and it should play the card on the first turn. Can you check it?

@AdriaGual  Thanks! I'm heading out now but will test your fixes when I get back later today and let you know if it resolves the issue. 👍
