### ISSUE TITLE
Multiple Issues Found After Recent Commits

### ISSUE THREAD

**Issue by NomadCHK** [AdriaGual/pokemon-pocket-bot#9]
#### 1. Card Info Handling
- Error occurs when `card["info"]` is `None` and trying to use `.get()` on it
- Card Info cant be None.

#### 2. UI Event Handling Issues
- Bot is not waiting for event selection properly
- Current behavior: Bot continues execution before user can click the select button
- Expected behavior: Bot should wait for user interaction before proceeding

#### 3. Deck Addition Logic
- Cards should never be added to deck without name or info
- Need proper handling for:
  - User canceling prompt name
  - Timeout scenarios
  - Invalid/not found card names

### Working Reference
- Last known working commit: 9437b94
- Current issues appeared after commit 86b85be

### Suggested Fixes
1. As you did with the logging of "selected_card" you must do to the block that adds to the deck, only add if selected_card.
2. Restore proper UI event waiting mechanism
3. Implement proper validation for card addition to deck
4. Check retry logic for invalid/missing card names

Please be free to ask me questions if you need any help.

### Edit:
Found problem on 9437b94:
- images/cards folder not created, so is not persisting, only works if we create the folder manually.

### Original comment :
_Originally posted by @NomadCHK in https://github.com/AdriaGual/pokemon-pocket-bot/issues/8#issuecomment-2465911666_

Thank you @supermopf , maybe we could add more things to your PR.
 @AdriaGual , I also did this here, but found more problems... 
 
After fixing that on my side i had some other errors, when card["info"] is None and try to do .get on it. I did a verification before the card["info"].gets and also on the play card method. But i found that something has changed on the logic on the last commits that makes info not work anymore. trying to point it.
i reversed before 86b85be58b77a872e4bd2d7cc97b4337fd34990c to the merge 9437b9490d81f1c56945beee8dc3f8aaa1ed41e1 and looks that info is working fine and bot is playing fine. @AdriaGual  on your side how are the tests of the lasts commits?

edit:
also find that the calls to the UI are now broken, the bot is not waiting the event to select the card anymore. please @AdriaGual  review your last commits since last merge 9437b9490d81f1c56945beee8dc3f8aaa1ed41e,

tested here 9437b9490d81f1c56945beee8dc3f8aaa1ed41e and its working fine
for example:
![image](https://github.com/user-attachments/assets/31aba024-eaaf-46a1-8ead-6b354d91dcf9)
in 9437b9490d81f1c56945beee8dc3f8aaa1ed41e  the bot waits for the user click select button, so can continue.
in the current commit the problem is that the bot continues behind the selection window, before we can click select. Also a card never must be added to the deck without name or info, so if the user cancel the prompt name or timeout, it must just continue to the next iteration, so it will ask again next time it loops, and if user enter a not found name, it will ask again. so we never get without the info.

**Comment by NomadCHK** [comment]
I've just pushed a stable version: https://github.com/NomadCHK/pokemon-pocket-bot/tree/ok110924

I've implemented some of your suggested changes from the previous commits. Would you mind taking a look and testing it when you have a chance? I wasn't able to incorporate all the changes yet, but I wanted to get your feedback on what I've done so far.

**Comment by AdriaGual** [comment]
@NomadCHK I see, I see, maybe the refactor of the logs was a bit too much, for now, I just reverted those commits from the main.

Since I see more people are wanting to contribute to the project, I'll also work by PRs, so people can test it better ❤️

**Comment by NomadCHK** [comment]
@AdriaGual Good idea. If you need any help let me know. Thank you, really appreciate
